package com.cablemanager;

import android.app.*;
import android.content.*;
import android.graphics.Color;
import android.graphics.drawable.GradientDrawable;
import android.net.Uri;
import android.os.Bundle;
import android.provider.Settings;
import android.text.Editable;
import android.text.TextWatcher;
import android.view.*;
import android.widget.*;
import androidx.appcompat.app.AppCompatActivity;
import org.apache.poi.ss.usermodel.*;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;
import org.json.*;
import java.io.*;
import java.text.NumberFormat;
import java.text.SimpleDateFormat;
import java.util.*;

public class MainActivity extends AppCompatActivity {
    private static final int PICK_EXCEL=1001, CREATE_EXCEL=1002, CREATE_BACKUP=1003, RESTORE_BACKUP=1004;
    private final ArrayList<Customer> customers=new ArrayList<>();
    private final ArrayList<JSONObject> payments=new ArrayList<>();
    private final ArrayList<String> billedMonths=new ArrayList<>();
    private final NumberFormat money=NumberFormat.getCurrencyInstance(new Locale("en","IN"));
    private LinearLayout root, content, bottom;
    private TextView title;
    private final int GREEN=Color.rgb(0,184,124), DARK=Color.rgb(0,155,110), BLUE=Color.rgb(23,105,220), BG=Color.rgb(246,248,250), TEXT=Color.rgb(30,42,55);
    private Customer selected;

    @Override public void onCreate(Bundle b){super.onCreate(b); getWindow().setStatusBarColor(Color.rgb(12,31,50));getWindow().setNavigationBarColor(Color.WHITE);getWindow().getDecorView().setSystemUiVisibility(View.SYSTEM_UI_FLAG_LIGHT_NAVIGATION_BAR); load(); showLogin();}

    private void base(String screenTitle, boolean nav){
        root=new LinearLayout(this); root.setOrientation(LinearLayout.VERTICAL); root.setBackgroundColor(BG);
        setContentView(root);
        LinearLayout bar=new LinearLayout(this); bar.setGravity(Gravity.CENTER_VERTICAL); bar.setPadding(dp(16),dp(8),dp(10),dp(8)); bar.setBackgroundColor(Color.rgb(0,157,113));
        TextView back=new TextView(this); back.setText("‹"); back.setTextColor(Color.WHITE);back.setTextSize(34);back.setGravity(Gravity.CENTER); back.setVisibility(screenTitle.equals("Dashboard")?View.GONE:View.VISIBLE); back.setOnClickListener(v->showDashboard());
        bar.addView(back,new LinearLayout.LayoutParams(dp(42),dp(54)));
        title=new TextView(this);title.setText(screenTitle);title.setTextColor(Color.WHITE);title.setTextSize(21);title.setTypeface(null,1);title.setGravity(Gravity.CENTER_VERTICAL);bar.addView(title,new LinearLayout.LayoutParams(0,dp(54),1));
        TextView more=new TextView(this);more.setText("⋮");more.setTextColor(Color.WHITE);more.setTextSize(30);more.setGravity(Gravity.CENTER);more.setOnClickListener(v->showMenu());bar.addView(more,new LinearLayout.LayoutParams(dp(42),dp(54)));
        root.addView(bar);
        content=new LinearLayout(this);content.setOrientation(LinearLayout.VERTICAL);content.setPadding(dp(14),dp(12),dp(14),dp(nav?8:14));root.addView(content,new LinearLayout.LayoutParams(-1,0,1));
        if(nav) buildBottom();
    }

    private void buildBottom(){bottom=new LinearLayout(this);bottom.setGravity(Gravity.CENTER);bottom.setBackgroundColor(Color.WHITE);String[] names={"⌂\nHome","♙\nCustomers","▣\nBilling","▤\nReports"};for(String n:names){TextView t=new TextView(this);t.setText(n);t.setTextSize(11);t.setGravity(Gravity.CENTER);t.setTextColor(Color.DKGRAY);t.setPadding(0,dp(7),0,dp(5));t.setOnClickListener(v->{String s=((TextView)v).getText().toString();if(s.contains("Home"))showDashboard();else if(s.contains("Customers"))showCustomers();else if(s.contains("Billing"))showPayments();else showReports();});bottom.addView(t,new LinearLayout.LayoutParams(0,dp(58),1));}root.addView(bottom);}

    private void showLogin(){
        LinearLayout page=new LinearLayout(this);page.setOrientation(LinearLayout.VERTICAL);page.setGravity(Gravity.CENTER);page.setPadding(dp(22),dp(20),dp(22),dp(20));page.setBackground(gradient(Color.rgb(0,151,145),Color.rgb(4,74,125)));
        TextView tv=label("📺\nMyCable Pro",34,Color.WHITE,true);tv.setGravity(Gravity.CENTER);page.addView(tv,new LinearLayout.LayoutParams(-1,dp(150)));
        TextView sub=label("Manage Customers\nCollect Payments\nGrow Your Business",14,Color.WHITE,false);sub.setGravity(Gravity.CENTER);page.addView(sub,new LinearLayout.LayoutParams(-1,dp(90)));
        EditText user=field("User Name");page.addView(user,new LinearLayout.LayoutParams(-1,dp(54)));
        EditText pass=field("Password");pass.setInputType(0x81);page.addView(pass,lp(0,12));
        Button login=button("LOGIN",GREEN);page.addView(login,lp(0,14));
        TextView hint=label("Default Password : 123456",11,Color.WHITE,false);hint.setGravity(Gravity.CENTER);page.addView(hint,lp(0,8));
        login.setOnClickListener(v->{if(pass.getText().toString().isEmpty()||pass.getText().toString().equals("123456"))showDashboard();else toast("Use password 123456");});setContentView(page);
    }

    private void showDashboard(){
        base("MyCable Pro",true); TextView hello=label("Vanakkam,\nAdmin",16,TEXT,true);content.addView(hello,lp(0,2));
        double due=0,advance=0;int active=0;for(Customer c:customers){due+=Math.max(0,c.dueAmount);advance+=Math.max(0,c.advanceAmount);if(!"Inactive".equalsIgnoreCase(c.status))active++;}
        LinearLayout stats=new LinearLayout(this);stats.setOrientation(LinearLayout.VERTICAL);addStatRow(stats, new String[]{"👥  Total Customers\n"+customers.size(),"✓  Active\n"+active}, new int[]{Color.rgb(215,235,255),Color.rgb(218,250,226)});addStatRow(stats,new String[]{"⊗  Due\n"+money.format(due),"₹  Advance\n"+money.format(advance)},new int[]{Color.rgb(255,224,224),Color.rgb(255,238,201)});content.addView(stats,lp(0,10));
        LinearLayout grid=new LinearLayout(this);grid.setOrientation(LinearLayout.VERTICAL);String[][] a={{"👥\nCustomers","▣\nBilling","₹\nCollection"},{"▤\nPackages","📍\nZones","▥\nReports"}};for(String[] row:a){LinearLayout r=new LinearLayout(this);for(String x:row){TextView t=card(x,15);r.addView(t,new LinearLayout.LayoutParams(0,dp(82),1));if(x.contains("Customers"))t.setOnClickListener(v->showCustomers());else if(x.contains("Billing"))t.setOnClickListener(v->showPayments());else if(x.contains("Collection"))t.setOnClickListener(v->showCollect(false));else if(x.contains("Packages"))t.setOnClickListener(v->showPackages());else if(x.contains("Zones"))t.setOnClickListener(v->showZones());else t.setOnClickListener(v->showReports());}grid.addView(r); }content.addView(grid,lp(0,10));
        LinearLayout q=new LinearLayout(this);Button imp=button("Import Excel",BLUE);Button exp=button("Export Excel",GREEN);q.addView(imp,new LinearLayout.LayoutParams(0,dp(52),1));q.addView(exp,lpw(8));content.addView(q,lp(0,10));imp.setOnClickListener(v->pickExcel());exp.setOnClickListener(v->createExport());
    }

    private void addStatRow(LinearLayout parent,String[] vals,int[] colors){LinearLayout r=new LinearLayout(this);for(int i=0;i<2;i++){TextView t=card(vals[i],15);t.setBackground(round(colors[i],14));t.setTextColor(TEXT);r.addView(t,new LinearLayout.LayoutParams(0,dp(76),1));}parent.addView(r,lp(0,6));}

    private void showCustomers(){base("Customers",true);LinearLayout searchRow=new LinearLayout(this);EditText s=field("Search name, mobile, box...");searchRow.addView(s,new LinearLayout.LayoutParams(0,dp(50),1));Button f=smallButton("☷");searchRow.addView(f,lpw(6));content.addView(searchRow);LinearLayout chips=new LinearLayout(this);for(String x:new String[]{"All","Due","Advance","Deactive"}){TextView c=chip(x);chips.addView(c,lpw(5));c.setOnClickListener(v->filterCustomers(s,((TextView)v).getText().toString()));}content.addView(chips,lp(0,8));ListView list=new ListView(this);list.setDivider(null);content.addView(list,new LinearLayout.LayoutParams(-1,0,1));f.setOnClickListener(v->showFilter());renderCustomers(list,customers);s.addTextChangedListener(new TextWatcher(){public void beforeTextChanged(CharSequence a,int b,int c,int d){}public void onTextChanged(CharSequence a,int b,int c,int d){renderCustomers(list,filter(a.toString(),"All"));}public void afterTextChanged(Editable e){}});}
    private ArrayList<Customer> filter(String q,String mode){ArrayList<Customer> out=new ArrayList<>();q=q.toLowerCase(Locale.US);for(Customer c:customers){boolean ok=q.isEmpty()||(c.name+" "+c.phone+" "+c.boxId+" "+c.address).toLowerCase(Locale.US).contains(q);if(ok)out.add(c);}return out;}
    private void filterCustomers(EditText s,String mode){if(mode.equals("Due"))toast("Due customers: "+countDue());else if(mode.equals("Advance"))toast("Advance customers: "+countAdvance());else if(mode.equals("Deactive"))toast("Inactive customers: "+countInactive());else toast("All customers: "+customers.size());}
    private int countDue(){int n=0;for(Customer c:customers)if(c.dueAmount>0)n++;return n;}private int countAdvance(){int n=0;for(Customer c:customers)if(c.advanceAmount>0)n++;return n;}private int countInactive(){int n=0;for(Customer c:customers)if("Inactive".equalsIgnoreCase(c.status))n++;return n;}

    private void renderCustomers(ListView list,List<Customer> data){ArrayAdapter<Customer> ad=new ArrayAdapter<Customer>(this,android.R.layout.simple_list_item_2,data){public View getView(int p,View v,ViewGroup g){View x=super.getView(p,v,g);Customer c=getItem(p);TextView a=x.findViewById(android.R.id.text1),b=x.findViewById(android.R.id.text2);a.setText(c.name+"    ₹ "+String.format(Locale.US,"%.0f",c.dueAmount));a.setTextSize(16);a.setTypeface(null,1);b.setText("Box: "+c.boxId+"\n"+(c.phone.isEmpty()?"":c.phone)+"  •  "+c.zone+"  •  "+(c.dueAmount>0?"Due":"Advance/OK"));b.setTextSize(12);return x;}};list.setAdapter(ad);list.setOnItemClickListener((p,v,pos,id)->{selected=data.get(pos);showDetails(selected);});}

    private void showDetails(Customer c){base("Customer Details",true);LinearLayout head=new LinearLayout(this);head.setGravity(Gravity.CENTER_VERTICAL);TextView avatar=card(c.name.length()>0?c.name.substring(0,1).toUpperCase():"C",22,BLUE);head.addView(avatar,new LinearLayout.LayoutParams(dp(62),dp(62)));TextView h=label(c.name+"\n"+c.phone+"\n"+c.boxId,15,TEXT,true);head.addView(h,lpw(12));content.addView(head);content.addView(info("Zone",c.zone));content.addView(info("Package",c.packageName+"  •  ₹"+fmt(c.packageCost)));content.addView(info("Status",c.status));LinearLayout balances=new LinearLayout(this);balances.addView(balance("Total Bill",c.packageCost));balances.addView(balance("Paid",Math.max(0,c.packageCost-c.dueAmount)));balances.addView(balance("Due",c.dueAmount));balances.addView(balance("Advance",c.advanceAmount));content.addView(balances,lp(0,10));LinearLayout actions=new LinearLayout(this);Button collect=button("Collect Payment",GREEN);Button hist=button("Payment History",BLUE);Button edit=button("Edit",Color.rgb(90,90,220));actions.addView(collect,lpw(4));actions.addView(hist,lpw(4));actions.addView(edit,lpw(4));content.addView(actions,lp(0,8));collect.setOnClickListener(v->showCollect(false));hist.setOnClickListener(v->showPaymentHistory(c));edit.setOnClickListener(v->showAdd(c));content.addView(info("Address",c.address));content.addView(info("Card / Smart Card",c.cardNo));}

    private void showAdd(Customer edit){base(edit==null?"Add Customer":"Edit Customer",true);EditText name=field("Customer Name *");EditText phone=field("Mobile Number *");EditText box=field("Box / Smart Card No *");EditText zone=field("Zone *");EditText pkg=field("Package *");EditText amt=field("Monthly Amount *");EditText address=field("Address");for(EditText e:new EditText[]{name,phone,box,zone,pkg,amt,address})content.addView(e,lp(0,7));if(edit!=null){name.setText(edit.name);phone.setText(edit.phone);box.setText(edit.boxId);zone.setText(edit.zone);pkg.setText(edit.packageName);amt.setText(String.valueOf(edit.packageCost));address.setText(edit.address);}RadioGroup rg=new RadioGroup(this);RadioButton ac=new RadioButton(this);ac.setText("Active");ac.setChecked(edit==null||!"Inactive".equalsIgnoreCase(edit.status));RadioButton in=new RadioButton(this);in.setText("Inactive");rg.addView(ac);rg.addView(in);content.addView(label("Status",13,TEXT,true));content.addView(rg);Button save=button("SAVE",GREEN);content.addView(save,lp(0,10));save.setOnClickListener(v->{Customer c=edit==null?new Customer():edit;c.name=name.getText().toString();c.phone=phone.getText().toString();c.boxId=box.getText().toString();c.zone=zone.getText().toString();c.packageName=pkg.getText().toString();c.packageCost=num(amt);c.address=address.getText().toString();c.status=ac.isChecked()?"Active":"Inactive";if(edit==null){if(c.boxId.isEmpty()){toast("Box ID required");return;}customers.add(c);}save();showDetails(c);});}

    private void showCollect(boolean advanceOnly){if(selected==null&&!customers.isEmpty())selected=customers.get(0);if(selected==null){showAdd(null);return;}Customer c=selected;base(advanceOnly?"Advance Payment":"Collect Payment",true);content.addView(info("Customer",c.name+"\n"+c.boxId));content.addView(info("Current Due",money.format(c.dueAmount)));content.addView(info("Advance Balance",money.format(c.advanceAmount)));RadioGroup type=new RadioGroup(this);RadioButton normal=new RadioButton(this);normal.setText("Normal Payment");normal.setChecked(!advanceOnly);RadioButton adv=new RadioButton(this);adv.setText("Advance Payment");adv.setChecked(advanceOnly);type.addView(normal);type.addView(adv);content.addView(label("Payment Type",13,TEXT,true));content.addView(type);EditText amount=field("Amount Paid");content.addView(amount,lp(0,8));Spinner mode=new Spinner(this);mode.setAdapter(new ArrayAdapter<String>(this,android.R.layout.simple_spinner_dropdown_item,new String[]{"Cash","Cheque","UPI/Other"}));content.addView(mode,lp(0,8));EditText notes=field("Notes (optional)");content.addView(notes,lp(0,8));Button save=button("SAVE PAYMENT",GREEN);content.addView(save,lp(0,10));save.setOnClickListener(v->{double a=num(amount);if(a<=0){toast("Enter amount");return;}boolean advPay=adv.isChecked();if(advPay)c.advanceAmount+=a;else{double used=Math.min(a,c.dueAmount);c.dueAmount-=used;double extra=a-used;if(extra>0)c.advanceAmount+=extra;}JSONObject p=new JSONObject();try{p.put("boxId",c.boxId);p.put("name",c.name);p.put("amount",a);p.put("type",advPay?"Advance":"Normal");p.put("mode",mode.getSelectedItem().toString());p.put("date",date());p.put("notes",notes.getText().toString());payments.add(p);}catch(Exception ignored){}save();toast("Payment saved");showDetails(c);});}

    private void showPaymentHistory(Customer c){base("Payment History",true);content.addView(info("Customer",c.name+"\n"+c.boxId));LinearLayout head=new LinearLayout(this);for(String s:new String[]{"Month","Bill","Paid","Date","Type"})head.addView(label(s,11,TEXT,true),new LinearLayout.LayoutParams(0,dp(40),1));content.addView(head);for(JSONObject p:payments){if(!p.optString("boxId").equals(c.boxId))continue;LinearLayout r=new LinearLayout(this);String[] vals={p.optString("date").length()>7?p.optString("date").substring(3):p.optString("date"),"₹"+fmt(c.packageCost),"₹"+fmt(p.optDouble("amount")),p.optString("date"),p.optString("type")};for(String x:vals)r.addView(label(x,10,Color.DKGRAY,false),new LinearLayout.LayoutParams(0,dp(44),1));content.addView(r);}}

    private void showPayments(){base("Billing",true);TextView s=label("Payment History",20,TEXT,true);content.addView(s);Button n=button("Normal Collection",GREEN);Button a=button("Advance Payment",BLUE);content.addView(n,lp(0,8));content.addView(a,lp(0,8));n.setOnClickListener(v->showCollect(false));a.setOnClickListener(v->showCollect(true));TextView total=label("\nTotal Due: "+money.format(totalDue())+"\nTotal Advance: "+money.format(totalAdvance()),18,TEXT,true);content.addView(total);}

    private void showReports(){base("Reports",true);TextView s=label("Summary",20,TEXT,true);content.addView(s);content.addView(card("₹ "+fmt(totalPaid())+"\nCollected",16),lp(0,8));content.addView(card("₹ "+fmt(totalDue())+"\nPending",16),lp(0,8));content.addView(card("₹ "+fmt(totalAdvance())+"\nAdvance",16),lp(0,8));Button day=button("Day Collection Report",BLUE);Button export=button("Export Report",GREEN);content.addView(day,lp(0,8));content.addView(export,lp(0,8));day.setOnClickListener(v->showDayReport());export.setOnClickListener(v->createExport());}

    private void showDayReport(){base("Day Collection Report",false);content.addView(label("Date : "+new SimpleDateFormat("MMM yyyy",Locale.US).format(new Date()),18,TEXT,true));String[] heads={"Date","Opening","Collected","Closing","Received"};LinearLayout hr=new LinearLayout(this);for(String x:heads)hr.addView(label(x,11,TEXT,true),new LinearLayout.LayoutParams(0,dp(42),1));content.addView(hr);double collected=0;for(JSONObject p:payments){if(p.optString("date").equals(date()))collected+=p.optDouble("amount");}content.addView(row(new String[]{date(),fmt(totalDue()+collected),fmt(collected),fmt(totalDue()),"0"}));content.addView(label("Total Collected   ₹"+fmt(collected),16,TEXT,true),lp(0,12));}

    private void showFilter(){base("Search / Filter",true);content.addView(label("Status",14,TEXT,true));for(String x:new String[]{"☑ Due","☐ Deactive","☐ Free","☐ No Payments","☑ Advance Payments"})content.addView(label(x,15,TEXT,false),lp(0,7));content.addView(label("Payment Type",14,TEXT,true),lp(0,14));for(String x:new String[]{"☑ Monthly","☐ Quarterly","☐ Half Yearly","☐ Yearly"})content.addView(label(x,15,TEXT,false),lp(0,7));Spinner z=new Spinner(this);z.setAdapter(new ArrayAdapter<String>(this,android.R.layout.simple_spinner_dropdown_item,new String[]{"Select Zone","AM PERUMAL KOVIL ST","AM MUTHUMARIYAMMAN KOVIL AP"}));content.addView(z,lp(0,12));Button apply=button("APPLY",GREEN);content.addView(apply,lp(0,10));apply.setOnClickListener(v->showCustomers());}

    private void showPackages(){base("Packages",true);for(String x:new String[]{"MONTHLY 200    ₹ 200.0","MONTHLY 280    ₹ 280.0","MONTHLY 300    ₹ 300.0","BASIC    ₹ 150.0","PREMIUM    ₹ 500.0"}){TextView t=label("●  "+x+"                 ✎  🗑",15,TEXT,false);t.setBackground(round(Color.WHITE,12));content.addView(t,lp(0,5));}}
    private void showZones(){base("Zones",true);for(String x:new String[]{"AM PERUMAL KOVIL ST","AM MUTHUMARIYAMMAN KOVIL AP","AM MAIN ROAD","AM FLAT","AM MUTAMIL NAGAR"}){TextView t=label(x+"                         ✎  🗑",14,TEXT,false);t.setBackground(round(Color.WHITE,12));content.addView(t,lp(0,5));}}

    private void showMenu(){base("MyCable Pro",false);String[] menu={"⚙  Dashboard","♙  Customers","▣  Billing","₹  Collection","▤  Packages","📍  Zones","▥  Reports","⇄  Export / Import","⚙  Settings","♙  Profile","↪  Logout"};for(String x:menu){TextView t=label(x,16,TEXT,false);t.setPadding(dp(10),dp(12),0,dp(12));content.addView(t);if(x.contains("Dashboard"))t.setOnClickListener(v->showDashboard());else if(x.contains("Customers"))t.setOnClickListener(v->showCustomers());else if(x.contains("Billing"))t.setOnClickListener(v->showPayments());else if(x.contains("Collection"))t.setOnClickListener(v->showCollect(false));else if(x.contains("Packages"))t.setOnClickListener(v->showPackages());else if(x.contains("Zones"))t.setOnClickListener(v->showZones());else if(x.contains("Reports"))t.setOnClickListener(v->showReports());else if(x.contains("Export"))t.setOnClickListener(v->showExportImport());else if(x.contains("Logout"))t.setOnClickListener(v->showLogin());}}

    private void showExportImport(){base("Export / Import",true);content.addView(card("📗  Export Data\nExport all customers and payments as an Excel file.",16),lp(0,8));Button ex=button("EXPORT",BLUE);content.addView(ex,lp(0,8));content.addView(card("📕  Import Data\nImport from a previously exported backup file.",16),lp(0,14));Button im=button("IMPORT",Color.rgb(120,70,220));content.addView(im,lp(0,8));content.addView(card("💾  Backup / Restore\nCreate or restore a complete app backup.",16),lp(0,14));Button bk=button("CREATE BACKUP",BLUE);Button rs=button("RESTORE BACKUP",Color.DKGRAY);content.addView(bk,lp(0,8));content.addView(rs,lp(0,8));ex.setOnClickListener(v->createExport());im.setOnClickListener(v->pickExcel());bk.setOnClickListener(v->createBackup());rs.setOnClickListener(v->restoreBackup());}

    private void showMonthly(){base("Monthly Billing",true);content.addView(label("Generate monthly bills for all active customers.",14,TEXT,false));EditText month=field("Month (e.g. October 2026)");month.setText(new SimpleDateFormat("MMMM yyyy",Locale.US).format(new Date()));content.addView(month,lp(0,10));content.addView(card("▣  Package Billing\nAutomatically create bills based on customer package amount.",15),lp(0,10));Button gen=button("GENERATE BILLS",GREEN);content.addView(gen,lp(0,10));gen.setOnClickListener(v->{generateBills(month.getText().toString());toast("Monthly bills generated");showDashboard();});}

    private void generateBills(String month){if(billedMonths.contains(month))return;for(Customer c:customers){if("Inactive".equalsIgnoreCase(c.status))continue;double bill=Math.max(0,c.packageCost);if(c.advanceAmount>0){double use=Math.min(c.advanceAmount,bill);c.advanceAmount-=use;bill-=use;}c.dueAmount+=bill;}billedMonths.add(month);save();}

    private void pickExcel(){Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.addCategory(Intent.CATEGORY_OPENABLE);i.setType("application/vnd.openxmlformats-officedocument.spreadsheetml.sheet");startActivityForResult(i,PICK_EXCEL);}
    private void createExport(){Intent i=new Intent(Intent.ACTION_CREATE_DOCUMENT);i.addCategory(Intent.CATEGORY_OPENABLE);i.setType("application/vnd.openxmlformats-officedocument.spreadsheetml.sheet");i.putExtra(Intent.EXTRA_TITLE,"MyCablePro_Export.xlsx");startActivityForResult(i,CREATE_EXCEL);}
    private void createBackup(){Intent i=new Intent(Intent.ACTION_CREATE_DOCUMENT);i.addCategory(Intent.CATEGORY_OPENABLE);i.setType("application/json");i.putExtra(Intent.EXTRA_TITLE,"MyCablePro_Backup.json");startActivityForResult(i,CREATE_BACKUP);}
    private void restoreBackup(){Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.addCategory(Intent.CATEGORY_OPENABLE);i.setType("application/json");startActivityForResult(i,RESTORE_BACKUP);}
    @Override protected void onActivityResult(int req,int result,Intent data){super.onActivityResult(req,result,data);if(result!=RESULT_OK||data==null)return;try{if(req==PICK_EXCEL){ExcelImporter.Result r=ExcelImporter.read(this,data.getData());for(Customer c:r.customers)upsert(c);save();toast("Imported "+r.customers.size()+" customers");showDashboard();}else if(req==CREATE_EXCEL)writeExcel(data.getData());else if(req==CREATE_BACKUP)writeBackup(data.getData());else if(req==RESTORE_BACKUP)readBackup(data.getData());}catch(Exception e){toast("Error: "+e.getMessage());}}
    private void upsert(Customer c){for(int i=0;i<customers.size();i++)if(customers.get(i).boxId.equals(c.boxId)){customers.set(i,c);return;}customers.add(c);}
    private void writeExcel(Uri u)throws Exception{try(OutputStream out=getContentResolver().openOutputStream(u);Workbook wb=new XSSFWorkbook()){Sheet s=wb.createSheet("Customers");String[] h={"BOX ID","CUSTOMER NAME","PHONE NO","ADDRESS","ZONE","PACKAGE NAME","PACKAGE COST","DUE AMOUNT","ADVANCE AMOUNT","STATUS"};Row r=s.createRow(0);for(int i=0;i<h.length;i++)r.createCell(i).setCellValue(h[i]);int row=1;for(Customer c:customers){Row x=s.createRow(row++);String[] v={c.boxId,c.name,c.phone,c.address,c.zone,c.packageName};for(int i=0;i<v.length;i++)x.createCell(i).setCellValue(v[i]);x.createCell(6).setCellValue(c.packageCost);x.createCell(7).setCellValue(c.dueAmount);x.createCell(8).setCellValue(c.advanceAmount);x.createCell(9).setCellValue(c.status);}wb.write(out);}toast("Excel exported");}
    private void writeBackup(Uri u)throws Exception{JSONObject root=new JSONObject();JSONArray a=new JSONArray();for(Customer c:customers)a.put(c.toJson());JSONArray p=new JSONArray();for(JSONObject x:payments)p.put(x);root.put("customers",a);root.put("payments",p);root.put("billedMonths",new JSONArray(billedMonths));try(OutputStream out=getContentResolver().openOutputStream(u)){out.write(root.toString(2).getBytes("UTF-8"));}toast("Backup created");}
    private void readBackup(Uri u)throws Exception{StringBuilder s=new StringBuilder();try(InputStream in=getContentResolver().openInputStream(u);BufferedReader r=new BufferedReader(new InputStreamReader(in))){String z;while((z=r.readLine())!=null)s.append(z);}JSONObject o=new JSONObject(s.toString());customers.clear();JSONArray a=o.optJSONArray("customers");if(a!=null)for(int i=0;i<a.length();i++)customers.add(Customer.fromJson(a.getJSONObject(i)));payments.clear();JSONArray p=o.optJSONArray("payments");if(p!=null)for(int i=0;i<p.length();i++)payments.add(p.getJSONObject(i));billedMonths.clear();JSONArray bm=o.optJSONArray("billedMonths");if(bm!=null)for(int i=0;i<bm.length();i++)billedMonths.add(bm.getString(i));save();showDashboard();toast("Backup restored");}

    private void load(){String s=getPreferences(MODE_PRIVATE).getString("customers","[]");try{JSONArray a=new JSONArray(s);for(int i=0;i<a.length();i++)customers.add(Customer.fromJson(a.getJSONObject(i)));}catch(Exception ignored){}String p=getPreferences(MODE_PRIVATE).getString("payments","[]");try{JSONArray a=new JSONArray(p);for(int i=0;i<a.length();i++)payments.add(a.getJSONObject(i));}catch(Exception ignored){}String b=getPreferences(MODE_PRIVATE).getString("billed","[]");try{JSONArray a=new JSONArray(b);for(int i=0;i<a.length();i++)billedMonths.add(a.getString(i));}catch(Exception ignored){}}
    private void save(){try{JSONArray a=new JSONArray();for(Customer c:customers)a.put(c.toJson());JSONArray p=new JSONArray();for(JSONObject x:payments)p.put(x);getPreferences(MODE_PRIVATE).edit().putString("customers",a.toString()).putString("payments",p.toString()).putString("billed",new JSONArray(billedMonths).toString()).apply();}catch(Exception ignored){}}

    private double totalDue(){double x=0;for(Customer c:customers)x+=Math.max(0,c.dueAmount);return x;}private double totalAdvance(){double x=0;for(Customer c:customers)x+=Math.max(0,c.advanceAmount);return x;}private double totalPaid(){double x=0;for(JSONObject p:payments)x+=p.optDouble("amount");return x;}
    private String date(){return new SimpleDateFormat("dd-MM-yyyy",Locale.US).format(new Date());}private String fmt(double x){return String.format(Locale.US,"%.0f",x);}private double num(EditText e){try{return Double.parseDouble(e.getText().toString().replace(",","").replace("₹",""));}catch(Exception x){return 0;}}
    private TextView info(String k,String v){TextView t=label(k+"\n"+v,13,TEXT,false);t.setBackground(round(Color.WHITE,10));return t;}
    private TextView balance(String k,double v){TextView t=label(k+"\n₹"+fmt(v),11,TEXT,true);t.setGravity(Gravity.CENTER);t.setBackground(round(Color.WHITE,10));return t;}
    private LinearLayout row(String[] a){LinearLayout r=new LinearLayout(this);for(String x:a)r.addView(label(x,10,TEXT,false),new LinearLayout.LayoutParams(0,dp(42),1));return r;}
    private EditText field(String hint){EditText e=new EditText(this);e.setHint(hint);e.setTextSize(14);e.setSingleLine(true);e.setPadding(dp(14),0,dp(14),0);e.setBackground(round(Color.WHITE,10));return e;}
    private Button button(String text,int color){Button b=new Button(this);b.setText(text);b.setTextColor(Color.WHITE);b.setTextSize(13);b.setAllCaps(false);b.setBackground(round(color,12));return b;}
    private Button smallButton(String text){return button(text,Color.WHITE);}
    private TextView chip(String x){TextView t=label(x,12,TEXT,true);t.setGravity(Gravity.CENTER);t.setBackground(round(Color.WHITE,18));return t;}
    private TextView card(String x,int size){return card(x,size,TEXT);}private TextView card(String x,int size,int color){TextView t=label(x,size,color,true);t.setGravity(Gravity.CENTER);t.setBackground(round(Color.WHITE,14));return t;}
    private TextView label(String text,int size,int color,boolean bold){TextView t=new TextView(this);t.setText(text);t.setTextSize(size);t.setTextColor(color);t.setTypeface(null,bold?1:0);t.setGravity(Gravity.CENTER_VERTICAL);return t;}
    private GradientDrawable round(int color,int rad){GradientDrawable g=new GradientDrawable();g.setColor(color);g.setCornerRadius(dp(rad));g.setStroke(dp(1),Color.argb(35,0,0,0));return g;}
    private GradientDrawable gradient(int a,int b){GradientDrawable g=new GradientDrawable(GradientDrawable.Orientation.TL_BR,new int[]{a,b});return g;}
    private LinearLayout.LayoutParams lp(int top,int bottom){LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,dp(52));p.setMargins(0,dp(top),0,dp(bottom));return p;}private LinearLayout.LayoutParams lpw(int margin){LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(0,dp(52),1);p.setMargins(dp(margin),0,0,0);return p;}private int dp(int n){return (int)(n*getResources().getDisplayMetrics().density+.5f);}private void toast(String s){Toast.makeText(this,s,Toast.LENGTH_SHORT).show();}
}
